import {DB} from './storage.js?v=5';import {requireAuth,bindShell,can,homeFor} from './auth.js?v=5';import {$,toast,uid,minutes,esc} from './utils.js';import {signature} from './signature.js?v=2';import {gallery} from './gallery.js';import {downloadPdf} from './pdf-download.js';
const session=await requireAuth();if(session.rol!=='public'&&!can(session,'trabajos'))location.href=homeFor(session);bindShell();try{await DB.refreshRecords()}catch(error){console.warn('Se usarán los registros disponibles en este dispositivo.',error)}const settings=DB.settings();$('#folio').textContent=`VP-${String(settings.nextFolio||1).padStart(6,'0')}`;$('#currentDate').textContent=new Intl.DateTimeFormat('es-MX',{dateStyle:'full'}).format(new Date());setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('es-MX'),1000);
DB.properties().forEach(x=>$('#predio').add(new Option(x,x)));$('#responsable').add(new Option('Seleccionar encargado',''));settings.responsibles.forEach(x=>$('#responsable').add(new Option(x,x)));$('#responsable').value=session.rol==='encargado'&&settings.responsibles.includes(session.nombre)?session.nombre:'';$('#fechaServicio').valueAsDate=new Date();
const serviceSection=$('#tipo').closest('.card');serviceSection.querySelector('h2').textContent='Tipo de mantenimiento';$('#tipo').previousElementSibling.textContent='Tipo de mantenimiento *';
const continuationPicker=document.createElement('div');continuationPicker.className='continuation-picker';continuationPicker.innerHTML=`<div class="field"><label>¿Es un servicio al que se le dará continuidad?</label><div class="pill-options"><input type="radio" name="esContinuacion" id="continuationNo" value="No" checked><label for="continuationNo">No</label><input type="radio" name="esContinuacion" id="continuationYes" value="Sí"><label for="continuationYes">Sí</label></div></div><div id="linkedServiceBox" class="field hidden"><label for="servicioOrigenId">Número de bitácora pendiente *</label><select name="servicioOrigenId" id="servicioOrigenId"><option value="">Seleccionar número de bitácora</option></select><small id="linkedServiceHelp">Solo aparecen servicios pendientes o en proceso que necesitan continuidad.</small><div id="linkedServiceSummary" class="linked-service-summary hidden"></div></div>`;serviceSection.querySelector('.grid').append(continuationPicker);
const openServices=DB.records().filter(record=>record.id&&(record.terminado==='No'||['Pendiente','En proceso'].includes(record.estado))&&record.continuidadEstado!=='Concluida').sort((a,b)=>new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt));openServices.forEach(record=>$('#servicioOrigenId').add(new Option(`${record.folio} · ${record.predio||'Sin predio'} · ${record.tipo||'Sin tipo'} · ${record.responsable||'Sin encargado'}`,record.id)));
const showLinkedService=()=>{const record=openServices.find(item=>item.id===$('#servicioOrigenId').value),box=$('#linkedServiceSummary');box.classList.toggle('hidden',!record);box.innerHTML=record?`<strong>${esc(record.folio)}</strong><span>${esc(record.cliente||'Sin cliente')} · ${esc(record.predio||'Sin predio')}</span><span>Estado: ${esc(record.estado||'Pendiente')} · Compromiso: ${esc(record.continuidadFecha||'Sin fecha')}</span>`:''};$('#servicioOrigenId').addEventListener('change',showLinkedService);
const toggleLinkedService=()=>{const linked=$('#continuationYes').checked;$('#linkedServiceBox').classList.toggle('hidden',!linked);$('#servicioOrigenId').required=linked;if(linked&&!openServices.length)$('#linkedServiceHelp').textContent='No hay servicios pendientes disponibles para dar continuidad.'};document.querySelectorAll('[name=esContinuacion]').forEach(option=>option.addEventListener('change',toggleLinkedService));toggleLinkedService();
const responsibleSection=$('#responsable').closest('.card');const performerField=document.createElement('div');performerField.className='field col-12';performerField.innerHTML='<label for="realizador">¿Quién realiza el servicio? *</label><input name="realizador" id="realizador" required placeholder="Escribe el nombre de la persona que realiza el trabajo">';responsibleSection.querySelector('.grid').append(performerField);
const signatureTitle=$('#vpSignature').closest('.card').querySelector('h2');signatureTitle.textContent='Firma de la persona responsable que realizó el trabajo';
const formActions=$('.form-actions');const saveNotice=document.createElement('div');saveNotice.className='save-notice';saveNotice.innerHTML='<strong>Importante:</strong> guarda esta bitácora para registrar tu trabajo.<span>Después descarga el PDF y compártelo con tu encargado.</span>';formActions.prepend(saveNotice);
const syncResponsible=()=>{$('#responsibleName').textContent=$('#realizador').value||$('#responsable').value||'—';$('#contractor').classList.toggle('hidden',$('#responsable').value!=='Contratista')};$('#responsable').onchange=syncResponsible;$('#realizador').addEventListener('input',syncResponsible);syncResponsible();
document.querySelectorAll('[name=terminado]').forEach(x=>x.onchange=()=>{const pending=$('#no').checked;$('#continuity').classList.toggle('hidden',!pending);$('#confirmText').textContent=pending?'Confirmo que recibí el servicio y conozco la fecha de continuidad.':'Confirmo que recibí el servicio descrito a conformidad.';['continuidadFecha','continuidadHora','continuidadMotivo'].forEach(n=>document.querySelector(`[name=${n}]`).required=pending)});
const clientSig=signature($('#clientSignature')),vpSig=signature($('#vpSignature'));$('#clearClient').onclick=clientSig.clear;$('#clearVp').onclick=vpSig.clear;const photos=gallery($('#photos'),$('#dropzone'),$('#preview'));
$('#captureForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]'),f=new FormData(e.currentTarget),d=Object.fromEntries(f.entries()),isLinked=d.esContinuacion==='Sí',origin=isLinked?DB.records().find(record=>record.id===d.servicioOrigenId):null;if(clientSig.isEmpty())return toast('Solicita la firma del cliente antes de guardar.','error');if(vpSig.isEmpty())return toast('Falta la firma de la persona que realizó el trabajo.','error');if(isLinked&&!origin)return toast('Selecciona la bitácora a la que darás continuidad.','error');d.id=uid();d.folio=DB.nextFolio();d.createdAt=new Date().toISOString();d.updatedAt=d.createdAt;d.createdBy=session.nombre;d.photos=photos.get();d.clientSignature=clientSig.data();d.vpSignature=vpSig.data();d.duration=minutes(d.horaInicio,d.horaTermino);d.esContinuidad=isLinked;d.continuidadDeId=origin?.id||'';d.continuidadDeFolio=origin?.folio||'';d.continuidadEstado=isLinked?($('#no').checked?'En proceso':'Concluida'):(d.terminado==='No'?'Pendiente':'No requerida');d.history=[{action:isLinked?`Continuidad de ${origin.folio}`:'Registro creado',at:d.createdAt,by:session.nombre}];if(d.responsable==='Contratista'&&!d.contratistaNombre)return toast('Captura el nombre del contratista','error');if(!$('#no').checked)d.estado='Concluido';button.disabled=true;button.textContent='Guardando…';try{const saved=await DB.saveRecord(d);if(origin){const stillPending=$('#no').checked;origin.estado=stillPending?'En proceso':'Concluido';origin.terminado=stillPending?'No':'Sí';origin.continuidadEstado=stillPending?'En proceso':'Concluida';origin.updatedAt=new Date().toISOString();origin.continuaciones=[...(origin.continuaciones||[]),{id:saved.id,folio:saved.folio,estado:saved.estado,fecha:saved.fechaServicio}];origin.history=[...(origin.history||[]),{action:stillPending?`Continuidad registrada en ${saved.folio}`:`Servicio y continuidad concluidos en ${saved.folio}`,at:origin.updatedAt,by:session.nombre}];await DB.saveRecord(origin)}DB.audit(isLinked?'Continuidad':'Creación',saved.folio);toast(isLinked&&!$('#no').checked?'Continuidad guardada; ambos servicios quedaron concluidos.':'Servicio guardado y sincronizado.');setTimeout(()=>location.href=session.rol==='admin'?'admin.html':'captura.html',1100)}catch(error){console.error(error);toast('No se pudo guardar en la nube. Revisa la conexión e inténtalo nuevamente.','error');button.disabled=false;button.textContent='Guardar Bitácora'}};
if(session.rol==='public'){const home=document.querySelector('[data-logout]');home.textContent='Inicio';home.onclick=()=>location.href='index.html'}
const publicNav=document.createElement('nav');publicNav.className='capture-nav';publicNav.setAttribute('aria-label','Navegación principal');publicNav.innerHTML=`<a href="index.html">Inicio</a><a class="active" href="captura.html">Trabajos</a>${session.rol==='public'?'<a href="login.html">Administración</a>':can(session,'administracion')?'<a href="admin.html">Administración</a>':''}`;document.querySelector('.topbar').insertBefore(publicNav,document.querySelector('.top-actions'));
document.querySelectorAll('[name=terminado]').forEach(option=>option.addEventListener('change',()=>{$('#estadoServicio').value=$('#no').checked?'Pendiente':'Concluido'}));
function capturePdfData(){return Object.fromEntries(new FormData($('#captureForm')).entries())}
function buildCapturePdf(){const d=capturePdfData(),images=photos.get(),date=d.fechaServicio?new Date(`${d.fechaServicio}T12:00:00`).toLocaleDateString('es-MX',{dateStyle:'long'}):'Sin fecha',folio=$('#folio').textContent,origin=d.esContinuacion==='Sí'?DB.records().find(record=>record.id===d.servicioOrigenId):null;$('#capturePdfBody').innerHTML=`<header class="capture-pdf-head"><div><span class="pdf-brand-pair"><img src="assets/logo/vallejo-properties.png" alt="Vallejo Properties"><img src="assets/logo/mantenimiento.jpg" alt="Mantenimiento"></span></div><div><small>BITÁCORA DE MANTENIMIENTO</small><strong>${esc(folio)}</strong><span>${esc(date)}</span></div></header><section class="capture-pdf-title"><h1>Registro de mantenimiento</h1><p>${esc(d.cliente||'Cliente sin capturar')} · ${esc(d.predio||'Predio sin seleccionar')}</p></section><section class="capture-pdf-info">${[['Empresa','Vallejo Properties'],['Cliente',d.cliente],['Predio',d.predio],['Espacio',d.espacio],['Tipo de mantenimiento',d.tipo],['Horario',`${d.horaInicio||'—'} a ${d.horaTermino||'—'}`],['Encargado',d.responsable],['Realizó el trabajo',d.realizador],['Estado',d.estado]].map(item=>`<div><small>${item[0]}</small><strong>${esc(item[1]||'—')}</strong></div>`).join('')}</section>${origin?`<section class="capture-pdf-block pending"><h2>Servicio de continuidad</h2><p>Esta bitácora da continuidad a <strong>${esc(origin.folio)}</strong> · ${esc(origin.tipo||'Sin tipo')} · ${esc(origin.predio||'Sin predio')}.</p></section>`:''}<section class="capture-pdf-block"><h2>Descripción del trabajo</h2><p>${esc(d.descripcion||'Sin descripción')}</p></section><section class="capture-pdf-block"><h2>Observaciones</h2><p>${esc(d.observaciones||'Sin observaciones')}</p></section>${d.terminado==='No'?`<section class="capture-pdf-block pending"><h2>Próxima continuidad del servicio</h2><p>${esc(d.continuidadFecha||'—')} · ${esc(d.continuidadHora||'—')}<br>${esc(d.continuidadMotivo||'Sin motivo capturado')}</p></section>`:''}<section class="capture-pdf-block"><h2>Evidencias fotográficas (${images.length})</h2><div class="capture-pdf-photos">${images.map((image,index)=>`<figure><img src="${image}"><figcaption>Evidencia ${index+1}</figcaption></figure>`).join('')||'<p>No se adjuntaron fotografías.</p>'}</div></section><section class="capture-pdf-signatures"><div><h2>Conformidad del cliente</h2><img src="${clientSig.data()}"><strong>${esc(d.clienteFirmaNombre||'—')}</strong><span>${esc(d.clienteCargo||'')}</span></div><div><h2>Persona que realizó el trabajo</h2><img src="${vpSig.data()}"><strong>${esc(d.realizador||'—')}</strong><span>${esc(d.responsable||'')}</span></div></section><footer>Bitácora Digital de Mantenimiento · Vallejo Properties</footer>`;$('#capturePdfDialog').showModal()}
$('#previewCapturePdf').onclick=buildCapturePdf;
$('#closeCapturePdf').onclick=()=>$('#capturePdfDialog').close();
$('#saveCapturePdf').textContent='Descargar PDF';
$('#saveCapturePdf').onclick=async()=>{
  const d=capturePdfData(),folio=$('#folio').textContent,button=$('#saveCapturePdf'),origin=d.esContinuacion==='Sí'?DB.records().find(record=>record.id===d.servicioOrigenId):null;
  button.disabled=true;button.textContent='Preparando PDF…';
  try{
    await downloadPdf({
      filename:`${folio}-bitacora.pdf`,
      title:`Bitácora de mantenimiento · ${folio}`,
      lines:[
        {label:'Fecha',value:d.fechaServicio},{label:'Cliente',value:d.cliente},{label:'Predio',value:d.predio},{label:'Espacio',value:d.espacio},
        {label:'Tipo de mantenimiento',value:d.tipo},{label:'Encargado',value:d.responsable},{label:'Persona que realizó el trabajo',value:d.realizador},
        {label:'Estado',value:d.estado},{label:'Horario',value:`${d.horaInicio||'—'} a ${d.horaTermino||'—'}`},
        {label:'Es continuidad de',value:origin?.folio||'No'},{label:'Descripción',value:d.descripcion},{label:'Observaciones',value:d.observaciones},
        {label:'Próxima continuidad',value:d.terminado==='No'?`${d.continuidadFecha||'—'} ${d.continuidadHora||''} · ${d.continuidadMotivo||''}`:'No requerida'}
      ],
      images:[...photos.get().map((src,index)=>({src,label:`Evidencia ${index+1}`})),{src:clientSig.data(),label:`Firma del cliente · ${d.clienteFirmaNombre||'Sin nombre'}`},{src:vpSig.data(),label:`Firma de quien realizó el trabajo · ${d.realizador||'Sin nombre'}`}]
    });
    toast('PDF descargado correctamente.');
  }catch(error){console.error(error);toast('No fue posible generar el PDF','error')}
  finally{button.disabled=false;button.textContent='Descargar PDF'}
};
