/* Vallejo Properties CMMS — HTML/CSS/JS estático. */
(()=>{"use strict";
const M=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],C=["#F58220","#2F8A57","#D99A18","#C74432","#BDBDBD","#444"];
const S={data:window.CMMS_DATA||{rows:[],locations:[]},rows:[],page:1,size:25,key:"opened",dir:-1},$=id=>document.getElementById(id);
const n=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim(),e=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const now=()=>new Date().toISOString().slice(0,10),days=(a,b)=>a&&b?Math.max(0,Math.round((Date.parse(b)-Date.parse(a))/864e5)):null,avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,pct=(a,b)=>b?Math.round(a/b*100):0;
const group=s=>{s=n(s);return s.includes("pendiente")?"Pendiente":s.includes("proceso")?"En proceso":s.includes("arrendatario")?"Arrendatario":s.includes("complet")?"Completado":"Otro"},closed=r=>["Completado","Arrendatario"].includes(group(r.status)),late=r=>!closed(r)&&r.commitment&&r.commitment<now(),critical=r=>n(r.priority).includes("critic")||(n(r.priority)==="alta"&&late(r)),sla=r=>Boolean(r.commitment&&r.closed&&r.closed<=r.commitment);
const fmt=d=>d?new Date(d+"T12:00:00").toLocaleDateString("es-MX",{day:"2-digit",month:"short",year:"numeric"}):"—";
const week=d=>{if(!d)return"";let x=new Date(d+"T12:00:00"),u=new Date(x);u.setDate(x.getDate()+4-(x.getDay()||7));let y=new Date(u.getFullYear(),0,1);return String(Math.ceil((((u-y)/864e5)+1)/7)).padStart(2,"0")};
const counts=(rows,fn)=>rows.reduce((m,r)=>{let k=fn(r)||"Sin dato";m[k]=(m[k]||0)+1;return m},{}),groups=(rows,fn)=>rows.reduce((m,r)=>{let k=fn(r)||"Sin dato";(m[k]??=[]).push(r);return m},{}),top=(o,z=10)=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,z),uniq=(k)=>[...new Set(S.data.rows.map(r=>r[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"es"));
function toast(t){let x=$("toast");x.textContent=t;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2600)}
function chartTip(ev,title,text){let tip=$("chartTooltip");tip.innerHTML=`<b>${e(title)}</b><span>${e(text)}</span>`;tip.style.left=ev.clientX+12+"px";tip.style.top=ev.clientY+12+"px";tip.classList.add("show")}
function hideChartTip(){$("chartTooltip").classList.remove("show")}
function clock(){let d=new Date();$("dateNow").textContent=d.toLocaleDateString("es-MX",{weekday:"short",day:"2-digit",month:"long",year:"numeric"});$("timeNow").textContent=d.toLocaleTimeString("es-MX")}
function options(){let weeks=[...new Set(S.data.rows.map(r=>week(r.opened)).filter(Boolean))].sort().map(x=>`Semana ${x}`),types=[...new Set(S.data.rows.flatMap(r=>r.types||splitTypes(r.type)))].sort((a,b)=>a.localeCompare(b,"es")),a=[["fMonth",M,"Todos"],["fYear",[...new Set(S.data.rows.map(r=>r.opened?.slice(0,4)).filter(Boolean))],"Todos"],["fWeek",weeks,"Todas"],["fClient",uniq("client"),"Todos"],["fLocation",uniq("location"),"Todos"],["fDepartment",uniq("department"),"Todos"],["fOwner",uniq("owner"),"Todos"],["fStatus",uniq("status"),"Todos"],["fPriority",uniq("priority"),"Todas"],["fType",types,"Todos"]];a.forEach(([id,items,all])=>{$(id).innerHTML=`<option>${all}</option>`+items.map(x=>`<option>${e(x)}</option>`).join("")})}
function filter(){let v=id=>$(id).value,t=n(v("fTicket")),q=n(v("fClientSearch"));S.rows=S.data.rows.filter(r=>(v("fMonth")==="Todos"||r.month===v("fMonth"))&&(v("fYear")==="Todos"||r.opened?.startsWith(v("fYear")))&&(v("fWeek")==="Todas"||`Semana ${week(r.opened)}`===v("fWeek"))&&(v("fClient")==="Todos"||r.client===v("fClient"))&&(v("fLocation")==="Todos"||r.location===v("fLocation"))&&(v("fDepartment")==="Todos"||r.department===v("fDepartment"))&&(v("fOwner")==="Todos"||r.owner===v("fOwner"))&&(v("fStatus")==="Todos"||r.status===v("fStatus"))&&(v("fPriority")==="Todas"||r.priority===v("fPriority"))&&(v("fType")==="Todos"||(r.types||splitTypes(r.type)).includes(v("fType")))&&(!t||n(r.id).includes(t))&&(!q||n(r.client).includes(q)));S.page=1;render()}
function render(){ $("recordCount").textContent=S.rows.length;$("sourceName").textContent=S.data.source||"Archivo cargado";kpis();traffic();alerts();eff();charts();analytics();properties();table()}
function kpis(){let r=S.rows,cl=r.filter(closed),tm=cl.map(x=>x.resolutionDays).filter(Number.isFinite),mainType=top(typeCounts(r),1)[0]||["Sin datos",0],a=[["Total de reportes",r.length,""],["Pendientes",r.filter(x=>group(x.status)==="Pendiente").length,"warning"],["En proceso",r.filter(x=>group(x.status)==="En proceso").length,"warning"],["Completados",r.filter(x=>group(x.status)==="Completado").length,"success"],["Con firma",r.filter(x=>x.signed).length,"success"],["Sin firma",cl.filter(x=>!x.signed).length,"warning"],["Arrendatario",r.filter(x=>group(x.status)==="Arrendatario").length,""],["Vencidos",r.filter(late).length,"alert"],["Críticos",r.filter(critical).length,"alert"],["Prioridad alta",r.filter(x=>n(x.priority)==="alta").length,"alert"],["Prioridad media",r.filter(x=>n(x.priority)==="media").length,"warning"],["Prioridad baja",r.filter(x=>n(x.priority)==="baja").length,"success"],["Resolución promedio",Math.round(avg(tm))+" d",""],["Atención estimada",Math.round(avg(r.map(x=>days(x.opened,x.updated||x.closed)).filter(Number.isFinite)))+" d",""],["Tipo principal",mainType[1],"",mainType[0]]];$("kpiGrid").innerHTML=a.map(x=>`<article class="kpi ${x[2]}"><label>${x[0]}</label><strong>${x[1]}</strong><small>${x[3]||"Selección actual"}</small></article>`).join("")}
function traffic(){let o=S.rows.filter(late).length,c=S.rows.filter(critical).length,soon=S.rows.filter(r=>!closed(r)&&r.commitment>=now()&&days(now(),r.commitment)<=2).length,l=o||c?"red":soon?"yellow":"",t=l==="red"?"Atención inmediata":l==="yellow"?"Operación preventiva":"Operación normal",p=l==="red"?`${o} vencidos y ${c} críticos.`:l==="yellow"?`${soon} próximos a vencer.`:"Sin alertas críticas.";$("trafficSignal").innerHTML=`<div class="signal-lamp ${l}"></div><div class="traffic-copy"><strong>${t}</strong><p>${p}</p></div>`}
function alerts(){let r=S.rows,op=r.filter(x=>!closed(x)),a=[["Tickets vencidos",r.filter(late).length,1],["Pendientes +7 días",op.filter(x=>days(x.opened,now())>7).length],["Pendientes +15 días",op.filter(x=>days(x.opened,now())>15).length,1],["Prioridad crítica",r.filter(critical).length,1],["Sin responsable",r.filter(x=>!x.owner||n(x.owner).includes("sin responsable")).length],["Sin fecha compromiso",op.filter(x=>!x.commitment).length],["Sin evidencia",r.filter(x=>!x.evidence).length],["Sin firma del cliente",r.filter(x=>closed(x)&&!x.signed).length,1]];$("alertsList").innerHTML=a.map(x=>`<div class="alert-row ${x[2]?"high":""}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
function eff(){let r=S.rows,cl=r.filter(closed),eligible=cl.filter(x=>x.commitment&&x.closed),ontime=eligible.filter(sla).length,lateClose=eligible.length-ontime,noDates=cl.length-eligible.length,tm=cl.map(x=>x.resolutionDays).filter(Number.isFinite),a=[[cl.length,"Tickets concluidos"],[r.length-cl.length,"Faltan por resolver"],[ontime,"Cerrados en fecha"],[lateClose,"Cerrados fuera de fecha"],[noDates,"Cerrados sin fechas comparables"],[Math.round(avg(tm))+" d","Tiempo de resolución"],[(tm.length?Math.round(Math.max(...tm)):0)+" d","Tiempo máximo"],[pct(r.filter(x=>x.signed).length,cl.length)+"%","Cierres con firma"]];$("efficiencyGrid").innerHTML=a.map(x=>`<div class="efficiency-item"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("")+`<p class="reconcile">ⓘ ${cl.length} concluidos = ${ontime} en fecha + ${lateClose} fuera de fecha + ${noDates} sin fechas comparables.</p>`}
function bars(id,o,z=8){let a=top(o,z),m=Math.max(1,...a.map(x=>x[1])),root=$(id);root.innerHTML=a.map(x=>`<div class="bar-item"><span>${e(x[0])}</span><div class="bar-track"><i style="width:${x[1]/m*100}%"></i></div><b>${x[1]}</b></div>`).join("");[...root.children].forEach((el,i)=>{el.onmousemove=ev=>chartTip(ev,a[i][0],`${a[i][1]} reportes`);el.onmouseleave=hideChartTip})}
function compact(id,headers,rows){$(id).innerHTML=`<div class="compact-wrap"><table class="compact-table"><thead><tr>${headers.map(x=>`<th>${e(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${e(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function breakdown(id,tableId,key,department=false){let rows=Object.entries(groups(S.rows,r=>r[key])).map(([name,a])=>{let solved=a.filter(closed).length,process=a.filter(x=>group(x.status)==="En proceso").length,pending=a.length-solved-process;return{name,total:a.length,solved,process,pending,unresolved:a.length-solved}}).sort((a,b)=>b.total-a.total),visible=rows.slice(0,10),root=$(id);root.innerHTML=visible.map(x=>`<div class="breakdown-row"><b>${e(x.name)}</b><div class="stack"><i class="solved" style="width:${pct(x.solved,x.total)}%"></i><i class="process" style="width:${pct(x.process,x.total)}%"></i><i class="pending" style="width:${pct(x.pending,x.total)}%"></i></div><span>${x.total}</span></div>`).join("");[...root.querySelectorAll(".stack")].forEach((el,i)=>{let x=visible[i];el.onmousemove=ev=>chartTip(ev,x.name,`Verde: ${x.solved} resueltos · Amarillo: ${x.process} en proceso · Rojo: ${x.pending} sin resolver`);el.onmouseleave=hideChartTip});compact(tableId,department?["Departamento","Resueltos","En proceso","Sin resolver","Total"]:["Responsable","Resueltos","En proceso","Sin resolver","Total"],rows.map(x=>[x.name,x.solved,x.process,x.pending,x.total]))}
function donut(o){let a=top(o,8),t=a.reduce((s,x)=>s+x[1],0)||1,u=0,ranges=[],st=a.map((x,i)=>{let b=u;u+=x[1]/t*360;ranges.push([b,u,x]);return`${C[i%C.length]} ${b}deg ${u}deg`}),donutEl=$("priorityDonut"),legend=$("priorityLegend");donutEl.style.background=`conic-gradient(${st})`;legend.innerHTML=a.map((x,i)=>`<div class="legend-item"><i style="background:${C[i%C.length]}"></i><span>${e(x[0])}</span><b>${x[1]}</b></div>`).join("");donutEl.onmousemove=ev=>{let r=donutEl.getBoundingClientRect(),dx=ev.clientX-(r.left+r.width/2),dy=ev.clientY-(r.top+r.height/2),angle=(Math.atan2(dx,-dy)*180/Math.PI+360)%360,item=ranges.find(x=>angle>=x[0]&&angle<x[1])?.[2];if(item)chartTip(ev,item[0],`${item[1]} reportes · ${pct(item[1],t)}%`)};donutEl.onmouseleave=hideChartTip;[...legend.children].forEach((el,i)=>{el.onmousemove=ev=>chartTip(ev,a[i][0],`${a[i][1]} reportes · ${pct(a[i][1],t)}%`);el.onmouseleave=hideChartTip})}
function charts(){let m=M.map(x=>S.rows.filter(r=>r.month===x).length),sm=counts(S.rows,r=>group(r.status)),pm=counts(S.rows,r=>r.priority),tm=typeCounts(S.rows);line("monthlyChart",m,C[0]);let z=m.filter(Boolean),v=z.at(-2)?Math.round((z.at(-1)-z.at(-2))/z.at(-2)*100):0;$("monthlyChange").textContent=`${v>=0?"▲":"▼"} ${Math.abs(v)}% vs. mes anterior`;bars("statusBars",sm);donut(pm);bars("typeBars",tm);compact("monthlyTable",["Mes","Reportes"],M.map((x,i)=>[x,m[i]]));compact("statusTable",["Estado","Cantidad"],top(sm,20));compact("priorityTable",["Prioridad","Cantidad"],top(pm,20));compact("typeTable",["Tipo","Cantidad"],top(tm,20))}
function line(id,data,color,second){let c=$(id),x=c.getContext("2d"),w=c.clientWidth||600,h=230,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.scale(d,d);let all=second?data.concat(second):data,m=Math.max(1,...all),px=i=>35+i*(w-50)/11,py=v=>205-v/m*175;x.clearRect(0,0,w,h);x.strokeStyle="#E7E7E7";for(let i=0;i<5;i++){x.beginPath();x.moveTo(35,20+i*43);x.lineTo(w-15,20+i*43);x.stroke()}[data,second].filter(Boolean).forEach((s,j)=>{x.strokeStyle=j?C[1]:color;x.lineWidth=2;x.beginPath();s.forEach((v,i)=>i?x.lineTo(px(i),py(v)):x.moveTo(px(i),py(v)));x.stroke();s.forEach((v,i)=>{x.fillStyle=j?C[1]:color;x.beginPath();x.arc(px(i),py(v),3,0,Math.PI*2);x.fill()})});x.font="9px Arial";x.fillStyle="#777";x.textAlign="center";M.forEach((q,i)=>x.fillText(q.slice(0,3),px(i),225));c.onmousemove=ev=>{let r=c.getBoundingClientRect(),i=Math.max(0,Math.min(11,Math.round((ev.clientX-r.left-35)/((w-50)/11)))),tip=$("chartTooltip"),label=id==="resolutionChart"?"Días":id==="openClosedChart"?"Registrados":"Reportes";tip.innerHTML=`<b>${M[i]}</b><span>${label}: ${Number(data[i]).toFixed(0)}${second?` · Resueltos: ${second[i]}`:""}</span>`;tip.style.left=ev.clientX+12+"px";tip.style.top=ev.clientY+12+"px";tip.classList.add("show")};c.onmouseleave=()=>$("chartTooltip").classList.remove("show")}
function ownerStats(){return Object.entries(groups(S.rows,r=>r.owner)).map(([name,a])=>{let cl=a.filter(closed),eligible=cl.filter(x=>x.commitment&&x.closed),tm=cl.map(r=>r.resolutionDays).filter(Number.isFinite);return{name,a:a.length,c:cl.length,u:a.length-cl.length,t:avg(tm),s:pct(eligible.filter(sla).length,eligible.length)}}).sort((a,b)=>b.c-a.c).slice(0,10)}
function ranking(id){let a=ownerStats();$(id).innerHTML=`<div class="ranking-row header"><span>#</span><span>Responsable</span><span>Asignados</span><span>Cerrados</span><span>Faltan</span><span>Tiempo resolución</span><span>Cumplimiento</span></div>`+a.map((x,i)=>`<div class="ranking-row"><span class="rank">${i+1}</span><b>${e(x.name)}</b><span>${x.a}</span><span>${x.c}</span><span>${x.u}</span><span>${x.t.toFixed(1)} d</span><span>${x.s}%<div class="meter"><i style="width:${x.s}%"></i></div></span></div>`).join("")}
function analytics(){breakdown("ownerBars","ownerTable","owner",false);breakdown("departmentBars","departmentTable","department",true);let registered=M.map(m=>S.rows.filter(r=>r.month===m).length),solved=M.map(m=>S.rows.filter(r=>r.month===m&&closed(r)).length),unsolved=registered.map((x,i)=>x-solved[i]);line("openClosedChart",registered,C[0],solved);compact("openClosedTable",["Mes","Registrados","Resueltos","No resueltos"],M.map((x,i)=>[x,registered[i],solved[i],unsolved[i]]));let response=S.rows.map(r=>days(r.opened,r.updated||r.closed)).filter(Number.isFinite),monthly=M.map((_,i)=>avg(S.rows.filter(r=>r.opened&&new Date(r.opened+"T12:00:00").getMonth()===i).map(r=>days(r.opened,r.updated||r.closed)).filter(Number.isFinite))),b0=response.filter(x=>x<=3).length,b1=response.filter(x=>x>=4&&x<=7).length,b2=response.filter(x=>x>7).length,noResponseDate=S.rows.length-response.length,slowest=Object.entries(groups(S.rows,r=>r.location)).map(([name,a])=>[name,avg(a.map(r=>days(r.opened,r.updated||r.closed)).filter(Number.isFinite))]).filter(x=>Number.isFinite(x[1])).sort((a,b)=>b[1]-a[1])[0]||["Sin datos",0];$("responseAverage").textContent=`${Math.round(avg(response))} días`;$("responseBands").innerHTML=`<div class="active"><b>0 a 3 días</b><span>${b0} respuestas ágiles</span></div><div><b>4 a 7 días</b><span>${b1} requieren atención</span></div><div class="urgent"><b>Más de 7 días</b><span>${b2} atención prioritaria</span></div><div class="slowest"><b>${e(slowest[0])}</b><span>Predio con mayor tardanza · ${Math.round(slowest[1])} días promedio</span></div>`;$("responseNote").textContent=`ⓘ ${response.length} reportes con fecha comparable; ${noResponseDate} sin actualización o cierre. Los tres rangos suman ${b0+b1+b2}.`;line("resolutionChart",monthly,C[0]);compact("resolutionTable",["Mes","Tiempo estimado (días)"],M.map((x,i)=>[x,Math.round(monthly[i])]));ranking("slaTable")}
function list(t,a,s=""){return`<div class="analysis-block"><h3>${t}</h3><ol>${a.map(x=>`<li>${e(x[0])} <b>${Number.isInteger(x[1])?x[1]:x[1].toFixed(1)}${s}</b></li>`).join("")}</ol></div>`}
function avgRank(k){return Object.entries(groups(S.rows,r=>r[k])).map(([x,a])=>[x,avg(a.map(r=>r.resolutionDays).filter(Number.isFinite))]).sort((a,b)=>b[1]-a[1]).slice(0,5)}
function properties(){let g=groups(S.rows,r=>r.location),cg=groups(S.rows,r=>r.client),lateRows=S.rows.filter(late),criticalRows=S.rows.filter(critical),affected=new Set(lateRows.concat(criticalRows).map(r=>r.location)).size,concluded=S.rows.filter(closed).length,inProcess=S.rows.filter(r=>group(r.status)==="En proceso").length,unresolved=S.rows.length-concluded-inProcess,topProperty=Object.entries(g).sort((a,b)=>b[1].length-a[1].length)[0]||["Sin datos",[]],level=lateRows.length||criticalRows.length?"red":"",title=level?"Predios con atención requerida":"Predios en operación normal";$("propertyTrafficSignal").innerHTML=`<div class="signal-lamp ${level}"></div><div class="traffic-copy"><strong>${title}</strong><p>${affected} predios con reportes vencidos o críticos.</p></div>`;$("propertyZeroMetrics").innerHTML=`<div><strong>${concluded}</strong><span>Reportes concluidos</span></div><div class="in-process"><strong>${inProcess}</strong><span>Reportes en elaboración</span></div><div class="unresolved"><strong>${unresolved}</strong><span>Reportes sin resolver</span></div><div class="top-property"><strong>${e(topProperty[0])}</strong><span>Predio con más incidencias · ${topProperty[1].length} reportes</span></div>`;$("propertyMap").innerHTML=Object.entries(g).sort((a,b)=>b[1].length-a[1].length).map(([x,a])=>{let p=a.filter(r=>group(r.status)!=="Completado"&&group(r.status)!=="Arrendatario"&&group(r.status)!=="En proceso").length,q=a.filter(r=>group(r.status)==="En proceso").length,d=a.filter(closed).length,l=a.some(late)?"red":p+q>2?"yellow":"";return`<div class="property-card ${l}"><h3>${e(x)}</h3><strong>${a.length}</strong><div class="property-stats"><span>Resueltos<b>${d}</b></span><span>En proceso de mantenimiento<b>${q}</b></span><span>Sin resolver<b>${p}</b></span></div></div>`}).join("");$("clientAnalysis").innerHTML=list("Más incidencias",top(counts(S.rows,r=>r.client),5))+list("Más pendientes",top(counts(S.rows.filter(x=>!closed(x)),r=>r.client),5));$("propertyAnalysis").innerHTML=list("Más incidencias",top(counts(S.rows,r=>r.location),5))+list("Más críticos",top(counts(S.rows.filter(critical),r=>r.location),5))+list("Más preventivos",top(counts(S.rows.filter(x=>n(x.type).includes("prevent")),r=>r.location),5));ranking("ownerRanking")}
const COL=[["id","Ticket"],["opened","Fecha"],["client","Cliente"],["location","Predio"],["department","Departamento"],["type","Tipo de servicio"],["owner","Responsable"],["priority","Prioridad"],["status","Estado"],["commitment","Fecha compromiso"],["closed","Fecha cierre"],["attention","Tiempo respuesta estimado"],["responseLevel","Nivel de atención"],["resolutionDays","Tiempo resolución"],["signed","Firma"]];
function cell(r,k){if(["opened","commitment","closed"].includes(k))return fmt(r[k]);if(k==="attention"){let z=days(r.opened,r.updated||r.closed);return z==null?"—":z+" días"}if(k==="responseLevel"){let z=days(r.opened,r.updated||r.closed);return z==null?"Sin dato":z<=3?"Óptima":z<=7?"Requiere atención":"Prioritaria"}if(k==="resolutionDays")return r[k]==null?"Abierto":r[k]+" días";if(k==="signed")return r.signed?"Sí":"No";if(k==="status"){let g=group(r.status),c=g==="Completado"?"done":g==="Pendiente"?"pending":g==="En proceso"?"process":"";return`<span class="status-pill ${c}">${e(r.status)}</span>`}return e(r[k])}
function table(){let q=n($("tableSearch").value),r=S.rows.filter(x=>!q||n(Object.values(x).join(" ")).includes(q));r.sort((a,b)=>String(a[S.key]??"").localeCompare(String(b[S.key]??""),undefined,{numeric:true})*S.dir);let p=Math.max(1,Math.ceil(r.length/S.size));S.page=Math.min(S.page,p);$("ticketHead").innerHTML=`<tr>${COL.map(x=>`<th data-k="${x[0]}">${x[1]} ${S.key===x[0]?(S.dir>0?"▲":"▼"):""}</th>`).join("")}</tr>`;$("ticketBody").innerHTML=r.slice((S.page-1)*S.size,S.page*S.size).map(x=>`<tr>${COL.map(y=>`<td>${cell(x,y[0])}</td>`).join("")}</tr>`).join("");$("pageInfo").textContent=`Página ${S.page} de ${p} · ${r.length} tickets`;$("prevPage").disabled=S.page<=1;$("nextPage").disabled=S.page>=p;$("ticketHead").querySelectorAll("th").forEach(x=>x.onclick=()=>{let k=x.dataset.k;if(S.key===k)S.dir*=-1;else S.key=k,S.dir=1;table()})}
function localDate(v){let p=x=>String(x).padStart(2,"0");return`${v.getFullYear()}-${p(v.getMonth()+1)}-${p(v.getDate())}`}
function xdate(v){if(v instanceof Date)return localDate(v);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+Math.floor(v)*864e5).toISOString().slice(0,10);if(typeof v==="string"){if(/^\d{4}-\d{2}-\d{2}/.test(v))return v.slice(0,10);let d=new Date(v);return isNaN(d)?null:localDate(d)}return null}
function lev(a,b){let m=Array.from({length:b.length+1},(_,i)=>[i]);for(let j=0;j<=a.length;j++)m[0][j]=j;for(let i=1;i<=b.length;i++)for(let j=1;j<=a.length;j++)m[i][j]=b[i-1]===a[j-1]?m[i-1][j-1]:Math.min(m[i-1][j-1],m[i][j-1],m[i-1][j])+1;return m[b.length][a.length]}
function canon(v){let z=n(v).toUpperCase(),alias={MASARAIK:"MASARIK",MASARYK:"MASARIK","PLAZA TLALNEPANTLA":"PLAZA TLANEPANTLA","CUAUTITLAN MASTER PARK":"CUATITLAN MASTER PARK",CEVA:"CEVA PONIENTE 140","MOLINA PARK 1":"EDUARDO MOLINA 1","MOLINA PARK 2":"EDUARDO MOLINA 2","PASAJE FERRERIA":"FERRERIA","QUIMIR PARK":"QUIMIR"};z=alias[z]||z;let exact=S.data.locations.find(x=>n(x).toUpperCase()===z);if(exact)return exact;let a=S.data.locations.map(x=>[x,lev(z,n(x).toUpperCase())/Math.max(z.length,n(x).length,1)]).sort((x,y)=>x[1]-y[1])[0];return a&&a[1]<=.22?a[0]:String(v||"SIN UBICACIÓN").trim().toUpperCase()}
function canonOwner(v){let z=n(v).replace(/\./g,"");return z==="ing tapia"?"Ing. Tapia":z==="isaac martin"?"Isaac Martin":String(v||"Sin responsable").trim()}
function canonClient(v){let raw=String(v||"Sin cliente").trim(),key=n(raw).replace(/[^a-z0-9]/g,"");return key==="drpromed"?"DRPROMED":raw}
function dedupeTickets(rows){let score=r=>Object.values(r).filter(v=>v!==null&&v!=="").length,m=new Map;rows.forEach(r=>{let p=m.get(r.id);if(!p||score(r)>score(p))m.set(r.id,r)});return[...m.values()]}
function splitTypes(v){return[...new Set(String(v||"Sin tipo").split(",").map(x=>x.trim()).filter(Boolean))]}
function typeCounts(rows){return rows.flatMap(r=>r.types||splitTypes(r.type)).reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})}
function parse(buf,name){let w=XLSX.read(buf,{type:"array",cellDates:true}),a=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:null});let r=a.filter(x=>String(x["ID Ticket"]||"").startsWith("V-ID-")).map(x=>{let o=xdate(x["Marca temporal"]),cl=xdate(x["Fecha de cierre"]),st=String(x.Estado||"Sin estatus"),types=splitTypes(x.Tipo);return{id:x["ID Ticket"],opened:o,month:x["Mes de seguimiento"]||(o?M[Number(o.slice(5,7))-1]:"Sin mes"),department:x.Departamento||"Sin departamento",client:canonClient(x["Razón Social"]||x["Nombre Completo"]),location:canon(x.Ubicación||"Sin predio"),space:x["Bodega / Piso"]||"Sin espacio",type:types.join(", "),types,status:st,priority:x.Prioridad||"Sin prioridad",commitment:xdate(x["Fecha de compromiso"]),updated:xdate(x["Ultima actualización"]),evidence:Boolean(x["Foto evidencia"]),owner:canonOwner(x.Responsable),closed:cl,resolutionDays:days(o,cl),signed:n(st).includes("con firma")&&!n(st).includes("sin firma"),notes:x["Nota Final"]||x.Notas||""}});r=dedupeTickets(r);if(!r.length)throw Error("No se encontraron tickets.");S.data={...S.data,source:name,rows:r};S.rows=r;options();render();toast(`${r.length} tickets únicos actualizados y predios homologados`)}
function exportX(){let a=S.rows.map(r=>({Ticket:r.id,Fecha:r.opened,Cliente:r.client,Predio:r.location,Departamento:r.department,"Tipo de servicio":r.type,Responsable:r.owner,Prioridad:r.priority,Estado:r.status,"Fecha Compromiso":r.commitment,"Fecha Cierre":r.closed,"Tiempo Resolución":r.resolutionDays,Firma:r.signed?"Sí":"No"})),w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(a),"Tickets");XLSX.writeFile(w,"Centro_Operaciones_Filtrado.xlsx")}
function redrawVisible(){if($("overview").classList.contains("active"))charts();if($("analytics").classList.contains("active"))analytics()}
function bind(){document.querySelectorAll(".nav-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-tabs button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.target).classList.add("active");requestAnimationFrame(redrawVisible)});document.querySelectorAll(".filter-grid select,.filter-grid input").forEach(x=>x.addEventListener(x.tagName==="INPUT"?"input":"change",filter));$("clearFilters").onclick=()=>{document.querySelectorAll(".filter-grid select").forEach(x=>x.selectedIndex=0);document.querySelectorAll(".filter-grid input").forEach(x=>x.value="");filter()};$("refreshBtn").onclick=()=>{filter();toast("Indicadores actualizados")};$("excelInput").onchange=async x=>{try{let f=x.target.files[0];if(f)parse(await f.arrayBuffer(),f.name)}catch(z){toast(z.message)}};$("tableSearch").oninput=()=>{S.page=1;table()};$("prevPage").onclick=()=>{S.page--;table()};$("nextPage").onclick=()=>{S.page++;table()};$("exportExcel").onclick=exportX;$("printBtn").onclick=()=>print();addEventListener("resize",redrawVisible)}
clock();setInterval(clock,1000);options();S.rows=S.data.rows;bind();render();
})();
